import Foundation

// ==============================================================================
// TypeScriptTokenizer TypeScript语言词法分析器
// 功能：对TypeScript代码进行词法分析，识别关键字、字符串、注释、数字、函数、类型等
// 位置：语法高亮系统的语言词法分析层
// ==============================================================================

class TypeScriptTokenizer: CLikeTokenizer {
    // MARK: - TypeScript关键字

    override var keywords: Set<String> {
        return [
            "break", "case", "catch", "class", "const", "continue", "debugger", "default",
            "delete", "do", "else", "enum", "export", "extends", "false", "finally",
            "for", "function", "if", "import", "in", "instanceof", "new", "null",
            "return", "super", "switch", "this", "throw", "true", "try", "typeof",
            "var", "void", "while", "with", "yield", "let", "static", "async", "await",
            "abstract", "as", "constructor", "declare", "get", "implements", "interface",
            "module", "namespace", "of", "private", "protected", "public", "readonly",
            "set", "type", "from", "default", "is", "keyof", "infer", "never", "unknown",
            "any", "string", "number", "boolean", "symbol", "bigint", "object",
            "undefined", "void", "never", "unknown", "any", "satisfies", "asserts",
            "global", "unique", "out", "override", "accessor"
        ]
    }

    // MARK: - TypeScript类型

    override var types: Set<String> {
        return [
            "String", "Number", "Boolean", "Symbol", "BigInt", "Object", "Array",
            "Function", "Error", "EvalError", "RangeError", "ReferenceError",
            "SyntaxError", "TypeError", "URIError", "AggregateError", "InternalError",
            "Promise", "Map", "Set", "WeakMap", "WeakSet", "WeakRef", "FinalizationRegistry",
            "Date", "RegExp", "Math", "JSON", "Intl", "ArrayBuffer", "SharedArrayBuffer",
            "Atomics", "DataView", "Float32Array", "Float64Array", "Int8Array",
            "Int16Array", "Int32Array", "Uint8Array", "Uint16Array", "Uint32Array",
            "Uint8ClampedArray", "BigInt64Array", "BigUint64Array", "Blob", "File",
            "FileReader", "FileList", "FormData", "URLSearchParams", "URL", "URI",
            "Headers", "Request", "Response", "FetchEvent", "AbortController",
            "AbortSignal", "TextEncoder", "TextDecoder", "TextDecoderStream",
            "TextEncoderStream", "CompressionStream", "DecompressionStream",
            "ReadableStream", "WritableStream", "TransformStream", "ReadableStreamDefaultReader",
            "WritableStreamDefaultWriter", "TransformStreamDefaultController",
            "ReadableByteStreamController", "ReadableStreamDefaultController",
            "WritableStreamDefaultController", "ByteLengthQueuingStrategy",
            "CountQueuingStrategy", "DOMException", "Event", "EventTarget",
            "CustomEvent", "EventEmitter", "MessageChannel", "MessagePort",
            "MessageEvent", "BroadcastChannel", "Worker", "SharedWorker",
            "ServiceWorker", "ServiceWorkerRegistration", "ServiceWorkerContainer",
            "Notification", "PushManager", "PushSubscription", "PushEvent",
            "Geolocation", "GeolocationPosition", "GeolocationPositionError",
            "GeolocationCoordinates", "Navigator", "Window", "Document", "Element",
            "HTMLElement", "HTMLDivElement", "HTMLSpanElement", "HTMLParagraphElement",
            "HTMLAnchorElement", "HTMLImageElement", "HTMLButtonElement", "HTMLInputElement",
            "HTMLFormElement", "HTMLSelectElement", "HTMLOptionElement", "HTMLTextAreaElement",
            "HTMLTableElement", "HTMLTableRowElement", "HTMLTableCellElement",
            "HTMLUListElement", "HTMLOListElement", "HTMLLIElement", "HTMLHeadElement",
            "HTMLBodyElement", "HTMLHtmlElement", "HTMLTitleElement", "HTMLMetaElement",
            "HTMLLinkElement", "HTMLStyleElement", "HTMLScriptElement", "HTMLCanvasElement",
            "CanvasRenderingContext2D", "WebGLRenderingContext", "WebGL2RenderingContext",
            "SVGElement", "SVGSVGElement", "Node", "NodeList", "HTMLCollection",
            "Attr", "NamedNodeMap", "CharacterData", "Text", "Comment", "CDATASection",
            "DocumentFragment", "ShadowRoot", "MutationObserver", "MutationRecord",
            "ResizeObserver", "ResizeObserverEntry", "IntersectionObserver",
            "IntersectionObserverEntry", "PerformanceObserver", "PerformanceEntry",
            "Performance", "PerformanceMark", "PerformanceMeasure", "PerformanceResourceTiming",
            "PerformanceNavigationTiming", "PerformancePaintTiming", "PerformanceLongTaskTiming",
            "PerformanceServerTiming", "PerformanceEventTiming", "History", "Location",
            "Screen", "ScreenOrientation", "VisualViewport", "ScrollTimeline",
            "Animation", "AnimationEffect", "KeyframeEffect", "AnimationTimeline",
            "DocumentTimeline", "CSSAnimation", "CSSTransition", "TransitionEvent",
            "AnimationEvent", "AnimationPlaybackEvent", "AnimationFrameProvider",
            "CSS", "CSSStyleDeclaration", "CSSRule", "CSSStyleRule", "CSSMediaRule",
            "CSSFontFaceRule", "CSSKeyframesRule", "CSSKeyframeRule", "CSSImportRule",
            "CSSStyleSheet", "StyleSheetList", "MediaQueryList", "MediaQueryListEvent",
            "MatchMedia", "CSSConditionRule", "CSSGroupingRule", "CSSPageRule",
            "CSSMarginRule", "CSSNamespaceRule", "CSSCounterStyleRule", "CSSFontFeatureValuesRule",
            "CSSLayerBlockRule", "CSSLayerStatementRule", "CSSPropertyRule",
            "CSSScopeRule", "CSSStartingStyleRule", "CSSSupportsRule", "CSSContainerRule",
            "CSSFontPaletteValuesRule", "CSSImageValue", "CSSKeywordValue",
            "CSSNumericValue", "CSSUnitValue", "CSSMathValue", "CSSMathSum",
            "CSSMathProduct", "CSSMathNegate", "CSSMathInvert", "CSSMathMin",
            "CSSMathMax", "CSSMathClamp", "CSSPositionValue", "CSSRotate",
            "CSSScale", "CSSSkew", "CSSSkewX", "CSSSkewY", "CSSTransformValue",
            "CSSTranslate", "CSSUnparsedValue", "CSSVariableReferenceValue",
            "StylePropertyMap", "StylePropertyMapReadOnly", "ElementCSSInlineStyle",
            "LinkStyle", "DocumentStyle", "ViewTransition", "ViewTransitionUpdateCallbackDone",
            "ViewTransitionReady", "ViewTransitionFinished", "ViewTransitionSkipTransition",
            "Clipboard", "ClipboardEvent", "ClipboardItem", "DataTransfer",
            "DataTransferItem", "DataTransferItemList", "DragEvent", "PointerEvent",
            "MouseEvent", "WheelEvent", "KeyboardEvent", "InputEvent", "CompositionEvent",
            "FocusEvent", "UIEvent", "TouchEvent", "Touch", "TouchList",
            "GestureEvent", "BeforeUnloadEvent", "HashChangeEvent", "PopStateEvent",
            "PageTransitionEvent", "PageSwapEvent", "PageRevealEvent", "StorageEvent",
            "Storage", "SessionStorage", "LocalStorage", "Cache", "CacheStorage",
            "IDBFactory", "IDBDatabase", "IDBObjectStore", "IDBIndex", "IDBCursor",
            "IDBCursorWithValue", "IDBKeyRange", "IDBTransaction", "IDBRequest",
            "IDBOpenDBRequest", "IDBVersionChangeEvent", "IDBVersionChangeRequest",
            "FileSystemHandle", "FileSystemFileHandle", "FileSystemDirectoryHandle",
            "FileSystemWritableFileStream", "FileSystemSyncAccessHandle",
            "StorageManager", "StorageEstimate", "LockManager", "Lock",
            "WakeLock", "WakeLockSentinel", "Permissions", "PermissionStatus",
            "Credential", "CredentialsContainer", "PasswordCredential", "FederatedCredential",
            "PublicKeyCredential", "AuthenticatorResponse", "AuthenticatorAttestationResponse",
            "AuthenticatorAssertionResponse", "AuthenticatorSelectionCriteria",
            "PublicKeyCredentialCreationOptions", "PublicKeyCredentialRequestOptions",
            "PublicKeyCredentialParameters", "PublicKeyCredentialDescriptor",
            "PublicKeyCredentialUserEntity", "PublicKeyCredentialRpEntity",
            "AuthenticatorAttestationResponseJSON", "AuthenticatorAssertionResponseJSON",
            "RegistrationResponseJSON", "AuthenticationResponseJSON", "PublicKeyCredentialJSON",
            "WebTransport", "WebTransportDatagramDuplexStream", "WebTransportReceiveStream",
            "WebTransportSendStream", "WebTransportBidirectionalStream", "WebTransportError",
            "WebSocket", "WebSocketStream", "WebSocketConnection", "RTCPeerConnection",
            "RTCSessionDescription", "RTCIceCandidate", "RTCPeerConnectionIceEvent",
            "RTCTrackEvent", "RTCDataChannel", "RTCDataChannelEvent", "RTCStatsReport",
            "MediaStream", "MediaStreamTrack", "MediaStreamTrackEvent", "MediaDevices",
            "MediaDeviceInfo", "InputDeviceInfo", "MediaTrackSupportedConstraints",
            "MediaTrackConstraints", "MediaTrackSettings", "MediaTrackCapabilities",
            "AudioContext", "AudioNode", "AudioParam", "AudioBuffer", "AudioBufferSourceNode",
            "AudioDestinationNode", "GainNode", "OscillatorNode", "BiquadFilterNode",
            "DelayNode", "DynamicsCompressorNode", "ConvolverNode", "AnalyserNode",
            "ChannelSplitterNode", "ChannelMergerNode", "PannerNode", "Listener",
            "StereoPannerNode", "WaveShaperNode", "ConstantSourceNode", "IIRFilterNode",
            "PeriodicWave", "MediaStreamAudioSourceNode", "MediaStreamAudioDestinationNode",
            "MediaElementAudioSourceNode", "AudioWorklet", "AudioWorkletNode",
            "AudioWorkletProcessor", "AudioWorkletGlobalScope", "BaseAudioContext",
            "OfflineAudioContext", "OfflineAudioCompletionEvent", "AudioScheduledSourceNode",
            "AudioListener", "AudioParamMap", "AudioNodeOptions", "AudioParamDescriptor",
            "AudioWorkletNodeOptions", "AudioWorkletProcessorConstructor",
            "HTMLMediaElement", "HTMLAudioElement", "HTMLVideoElement", "AudioTrackList",
            "VideoTrackList", "TextTrackList", "TextTrack", "TextTrackCue",
            "TextTrackCueList", "VTTCue", "TimeRanges", "MediaError", "MediaSource",
            "SourceBuffer", "SourceBufferList", "MediaKeySystemAccess", "MediaKeys",
            "MediaKeySession", "MediaKeyStatusMap", "MediaKeyMessageEvent",
            "MediaEncryptedEvent", "MediaKeyError", "MediaKeyNeededEvent",
            "PictureInPictureWindow", "PictureInPictureEvent", "Presentation",
            "PresentationRequest", "PresentationConnection", "PresentationConnectionList",
            "PresentationAvailability", "PresentationReceiver", "PresentationConnectionAvailableEvent",
            "PresentationConnectionCloseEvent", "XRSystem", "XRSession", "XRSpace",
            "XRReferenceSpace", "XRBoundedReferenceSpace", "XRView", "XRViewerPose",
            "XRPose", "XRJointPose", "XRHand", "XRJointSpace", "XRFrame",
            "XRInputSource", "XRInputSourceArray", "XRInputSourceEvent", "XRInputSourcesChangeEvent",
            "XRSessionEvent", "XRRenderState", "XRWebGLLayer", "XRProjectionLayer",
            "XRQuadLayer", "XRCylinderLayer", "XREquirectLayer", "XRCompositionLayer",
            "XRLayer", "XRSubImage", "XRWebGLSubImage", "XRViewPose", "XRTransientInputHitTestSource",
            "XRHitTestSource", "XRHitTestResult", "XRTransientInputHitTestResult",
            "XRAnchor", "XRAnchorSet", "XRLightEstimate", "XRLightProbe",
            "XRDepthInformation", "XRCPUDepthInformation", "XRWebGLDepthInformation",
            "XRMesh", "XRMeshDetectorResult", "XRPlane", "XRPlaneDetectorResult",
            "XRSemanticLabel", "Gamepad", "GamepadButton", "GamepadEvent",
            "GamepadHapticActuator", "GamepadPose", "GamepadMappingType", "HID",
            "HIDDevice", "HIDInputReportEvent", "HIDConnectionEvent", "USB",
            "USBDevice", "USBInterface", "USBAlternateInterface", "USBEndpoint",
            "USBConfiguration", "USBTransferInResult", "USBTransferOutResult",
            "USBConnectionEvent", "Serial", "SerialPort", "SerialOptions",
            "SerialInputSignals", "SerialOutputSignals", "SerialConnectionEvent",
            "Bluetooth", "BluetoothDevice", "BluetoothRemoteGATTServer", "BluetoothRemoteGATTService",
            "BluetoothRemoteGATTCharacteristic", "BluetoothRemoteGATTDescriptor",
            "BluetoothCharacteristicProperties", "BluetoothAdvertisingEvent",
            "BluetoothManufacturerDataMap", "BluetoothServiceDataMap", "BluetoothUUID",
            "NFCReader", "NFCTag", "NFCReaderError", "NFCWatchOptions", "NFCReadingEvent",
            "NDEFReader", "NDEFWriter", "NDEFMessage", "NDEFRecord", "NDEFRecordInit",
            "NDEFReadingEvent", "NDEFErrorEvent", "NDEFRecordType", "NDEFRecordMedia",
            "MIDIInput", "MIDIOutput", "MIDIPort", "MIDIAccess", "MIDIConnectionEvent",
            "MIDIMessageEvent", "WebAssembly", "WebAssembly.Module", "WebAssembly.Instance",
            "WebAssembly.Memory", "WebAssembly.Table", "WebAssembly.CompileError",
            "WebAssembly.LinkError", "WebAssembly.RuntimeError", "WebAssembly.Global",
            "WebAssembly.Tag", "WebAssembly.Exception", "WebAssembly.Function",
            "WebAssembly.Suspending", "WebAssembly.Promise", "WebAssembly.JSType",
            "WebAssembly.ValueType", "WebAssembly.Externref", "WebAssembly.Anyref",
            "WebAssembly.Funcref", "WebAssembly.Nullref", "WebAssembly.I31ref",
            "WebAssembly.StructType", "WebAssembly.ArrayType", "WebAssembly.FieldType",
            "WebAssembly.PackedType", "WebAssembly.Mutability", "WebAssembly.GlobalType",
            "WebAssembly.TableType", "WebAssembly.MemoryType", "WebAssembly.FunctionType",
            "WebAssembly.ExportType", "WebAssembly.ImportType", "WebAssembly.ModuleImports",
            "WebAssembly.ModuleExports", "WebAssembly.ModuleImports", "WebAssembly.CompileError",
            "WebAssembly.LinkError", "WebAssembly.RuntimeError", "WebAssembly.Tag",
            "WebAssembly.Exception", "WebAssembly.Function", "WebAssembly.Suspending",
            "WebAssembly.Promise", "WebAssembly.JSType", "WebAssembly.ValueType",
            "WebAssembly.Externref", "WebAssembly.Anyref", "WebAssembly.Funcref",
            "WebAssembly.Nullref", "WebAssembly.I31ref", "WebAssembly.StructType",
            "WebAssembly.ArrayType", "WebAssembly.FieldType", "WebAssembly.PackedType",
            "WebAssembly.Mutability", "WebAssembly.GlobalType", "WebAssembly.TableType",
            "WebAssembly.MemoryType", "WebAssembly.FunctionType", "WebAssembly.ExportType",
            "WebAssembly.ImportType", "WebAssembly.ModuleImports", "WebAssembly.ModuleExports"
        ]
    }

    // MARK: - 初始化

    init() {
        super.init(language: .typescript)
    }
}
